<?php
include_once 'Weapon.php';
class Excalibur extends Weapon
{
    public function isCritical($critical) {
        return parent::isCritical($critical); // TODO: Change the autogenerated stub
    }
}